# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provision :shell, path: "../admindojo/internal/bootstrap.sh"
    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "../admindojo", "/admindojo"

    config.vm.provider "virtualbox" do |vb|
        vb.name = 'ub18-apache-1'
        vb.memory = 2048
        vb.cpus = 2
        # performance tweak
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
    end

    if ENV['VAGRANT_TEST'] = 'testing'
    #$env:VAGRANT_TEST = "testing";vagrant up
        config.vm.provision "shell", inline: 'find /vagrant/training/ -name test.sh -exec {} \;'
        config.vm.provision "shell", inline: "bash /admindojo/internal/testing.sh"
    end

end