# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vbguest.auto_update = false

    config.vm.box = "ubuntu/bionic64"
    config.vm.provision :shell, path: "../admindojo/internal/bootstrap.sh"
    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "../admindojo", "/admindojo"

    config.vm.provider "virtualbox" do |vb|
        vb.name = 'webserver-apache-basic-1'
        vb.memory = 2048
        vb.cpus = 2
        # performance tweak
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
    end

end